interface IO365Contact {
  assistantName?: string
  birthday?: string
  businessAddress?: IO365PhysicalAddress
  businessHomepage?: string
  businessPhones?: string[]
  categories?: string[]
  changeKey?: string
  children?: string[]
  companyName?: string
  createdDateTime?: string
  department?: string
  displayName?: string
  emailAddresses?: IO365EmailAddress[]
  fileAs?: string
  generation?: string
  givenName?: string
  homeAddress?: IO365PhysicalAddress
  homePhones?: string[]
  id?: string
  imAddress?: string[]
  initials?: string
  jobTitle?: string
  lastModifiedDateTime?: string
  manager?: string
  middleName?: string
  mobilePhone?: string
  nickName?: string
  officeLocation?: string
  otherAddress?: IO365PhysicalAddress
  parentFolderId?: string
  personalNotes?: string
  profession?: string
  spouseName?: string
  surname?: string
  title?: string
  imAddresses?: string[]
}
